ULTRAPLAN_KEYWORD = "ultraplan"
ULTRAPLAN_TELEPORT_SENTINEL = "__ULTRAPLAN_TELEPORT_LOCAL__"
APPROVED_PLAN_MARKERS = [
    "## Approved Plan (edited by user):\n",
    "## Approved Plan:\n",
]
DEFAULT_POLL_INTERVAL_SECONDS = 3.0
DEFAULT_MAX_CONSECUTIVE_FAILURES = 5
DEFAULT_ULTRAPLAN_TIMEOUT_SECONDS = 30 * 60
DEFAULT_REMOTE_PERMISSION_MODE = "plan"
DEFAULT_REMOTE_DESCRIPTION = "Refine local plan"
